[core]
# Enable plugins for core screen rendering and mouse management
plugins = alpha animate move resize place expo scale blur

# Disable virtual workspaces for the login manager environment 
vwidth = 1
vheight = 1

[animate]
# Add transition eye-candy to the greeter panel load-in
open_animation = fade
close_animation = fade
duration = 300
